---
title: "Coastal Swell (last 5 records)"
---

```{r, include=FALSE}
#library(tidyverse)
library(dplyr)
library(tidyr)
library(lubridate)
library(gt)
```

```{r, echo=FALSE, warning=FALSE, }

df_data <- read.csv('swell_data.csv', header = TRUE)
df_data$record_date <- dmy_hm(df_data$record_date)
#df_data$write_date <- ymd_hms(df_data$write_date)
df_data <- df_data %>% 
  select(-write_date) 
df_data <- unique(df_data)

df_data$direction <- as.numeric(df_data$direction)
df_data$peak_period <- as.numeric(df_data$peak_period)
df_tidy <- tail(df_data) %>% 
  arrange(desc(record_date)) %>% 
  select(-highest_tenth) %>% 
  rename("Dir" = compass) %>% 
  rename("Bearing" = direction) %>% 
  rename("Peak Period" = peak_period) %>% 
  rename("Mean Period" = mean_period) %>% 
  rename("Max Wave" = max_wave) %>% 
  rename("Sig Height" = sig_height)

numeric_cols <- c("Bearing", "Peak Period", "Mean Period", "Max Wave", "Sig Height")
char_cols <- c("Dir")

df_numeric <- df_tidy %>% 
  select(record_date, all_of(numeric_cols)) %>% 
  mutate(record_date = as.character(record_date)) %>% 
  pivot_longer(cols = -record_date, names_to = "metric", values_to = "value") %>% 
  pivot_wider(names_from = record_date, values_from = value) %>% 
  mutate(across(everything(), as.character))

df_char <- df_tidy %>% 
  select(record_date, all_of(char_cols)) %>% 
  mutate(record_date = as.character(record_date)) %>% 
  pivot_longer(cols = -record_date, names_to = "metric", values_to = "value") %>% 
  pivot_wider(names_from = record_date, values_from = value)

df_table <- bind_rows(df_char, df_numeric)

gt(df_table)
```
